In [2]:
import pandas as pd
import pickle

In [3]:
with open('C:/Users/ASUS/anaconda3/data_scentics/data/interim/books_data.pkl', 'rb') as f:
    books_data = pickle.load(f)

with open('C:/Users/ASUS/anaconda3/data_scentics/data/interim/ratings_data.pkl', 'rb') as f:
    ratings_data= pickle.load(f)

with open('C:/Users/ASUS/anaconda3/data_scentics/data/interim/users_data.pkl', 'rb') as f:
    users_data= pickle.load(f)

In [4]:
# create sample data
sample = ratings_data.sample(n=1000, random_state=42)
ISBN = sample.iloc[1]['ISBN']

In [5]:
def correlation(ISBN):

    # Filtered subset of ratings_data based on ISBN
    ratings_data_filtered = ratings_data[ratings_data['ISBN'].isin(['0590353403', '0439136350', '0439139597','0439064864', '8445071408'])]

    # Concatenate the filtered subset with the sample DataFrame
    concatenated_df = pd.concat([ratings_data_filtered, sample], ignore_index=True)
    concatenated_df = concatenated_df.drop_duplicates()

    # create pivoted matrix
    pivoted_df = concatenated_df.pivot(index='User-ID', columns='ISBN', values='Book-Rating')
    pivoted_df.fillna(0, inplace=True)
    #pivoted_df

    # calculate correlation matrix
    correlation = pivoted_df.corr()

    correlation = correlation.loc[ISBN].reset_index(name = 'Index')

    correlation  = correlation[(correlation['Index'] > 0) & (correlation['Index'] < 1)]

    books = books_data.loc[books_data['ISBN'].isin(correlation['ISBN'])]

    return(books)

In [6]:
books_data.loc[books_data['ISBN'] == '0590353403']

,ISBN,Book-Author,Book-Title,Year-Of-Publication,Publisher,Language
2809,0590353403,J.K.ROWLING,HARRY POTTER AND THE SORCERER'S STONE BOOK 1,1998,SCHOLASTIC,EN

In [7]:
books_data.loc[books_data['ISBN'].isin(sample['ISBN'])]

,ISBN,Book-Author,Book-Title,Year-Of-Publication,Publisher,Language
26,0971880107,RIC.SHAPERO,WILD ANIMUS,2004,TOO FAR,EN
46,0553582747,DEA.KOONTZ,FROM THE CORNER OF HIS EYE,2001,BANTAM BOOKS,EN
113,0446608653,SANDR.BROWN,THE ALIBI,2000,WARNER BOOKS,EN
114,0446612545,JAME.PATTERSON,THE BEACH HOUSE,2003,WARNER BOOKS,EN
118,0671027360,DA.BROWN,ANGELS &AMP; DEMONS,2001,POCKET STAR,EN
...,...,...,...,...,...,...
265706,0671660578,SARA.SHANKMAN,KEEPING SECRETS,1988,SIMON &AMP; SCHUSTER,EN
265891,1883319080,MOSH.FELDENKRAIS,BODY AWARENESS AS HEALING THERAPY THE CASE OF ...,1994,NORTH ATLANTIC BOOKS,EN
266275,0812501810,WALTE.JO.WILLIAMS,FACETS,1991,TOR BOOKS (MM),EN
268349,0373195508,BEVERL.BIRD,TEN WAYS TO WIN HER MAN SILHOUETTE ROMANCE,2001,SILHOUETTE,EN
268559,1576732371,SUSA.WIS.BAUER,THOUGH THE DARKNESS HIDE THEE,1998,MULTNOMAH,EN

In [8]:
ISBN = '0590353403'
correlation(ISBN)

,ISBN,Book-Author,Book-Title,Year-Of-Publication,Publisher,Language
1721,0060192119,JOH.COLAPINTO,AS NATURE MADE HIM THE BOY WHO WAS RAISED AS A...,2000,HARPERCOLLINS PUBLISHERS,EN
3839,0439136350,J.K.ROWLING,HARRY POTTER AND THE PRISONER OF AZKABAN BOOK 3,1999,SCHOLASTIC,EN
5431,0439139597,J.K.ROWLING,HARRY POTTER AND THE GOBLET OF FIRE BOOK 4,2000,SCHOLASTIC,EN
5432,0439064864,J.K.ROWLING,HARRY POTTER AND THE CHAMBER OF SECRETS BOOK 2,1999,SCHOLASTIC,EN
11765,8807813025,ALESSANDR.BARICCO,"NOVOCENTO, UN MONOLOGO",2003,DISTRIBOOKS INC,EN
17420,1558746099,JAC.CANFIELD,CHICKEN SOUP FOR THE KID'S SOUL 101 STORIES O...,1998,HCI,EN
25676,0425155188,J.D.ROBB,RAPTURE IN DEATH,1996,BERKLEY PUBLISHING GROUP,EN
111751,0486296024,THOMA.PAINE,COMMON SENSE DOVER THRIFT EDITIONS,1997,DOVER PUBLICATIONS,EN
118722,0393974871,M.H.ABRAMS,THE NORTON ANTHOLOGY OF ENGLISH LITERATURE,1999,W.W. NORTON &AMP; COMPANY,EN
155166,0812036875,HELG.FRITZSCHE,"BANTAMS HUSBANDRY AND CARE, DISEASES, AND BREE...",1986,BARRON'S EDUCATIONAL SERIES,NO
169193,0385196156,ANTHON.D.MELLO,THE SONG OF THE BIRD,1984,IMAGE,EN
192191,037570633X,ELIZ.MINOT,THE TINY ONE VINTAGE CONTEMPORARIES,2000,VINTAGE BOOKS USA,EN
231809,1576736997,ROBI.LE.HATCHER,THE STORY JAR,2001,MULTNOMAH,EN
248790,039591910X,H.A.REY,CURIOUS GEORGE FEEDS THE ANIMALS,1998,HOUGHTON MIFFLIN CO,EN