In [23]:
import pandas as pd
import pickle

In [24]:
with open('data/interim/books_data.pkl', 'rb') as f:
    books_data = pickle.load(f)

with open('data/interim/ratings_data.pkl', 'rb') as f:
    ratings_data= pickle.load(f)

with open('data/interim/users_data.pkl', 'rb') as f:
    users_data= pickle.load(f)

In [25]:
books_data.info

<bound method DataFrame.info of               ISBN           Book-Author  \
0       0195153448    MARK P. O. MORFORD
1       0002005018  RICHARD BRUCE WRIGHT
2       0060973129          CARLO D'ESTE
3       0374157065      GINA BARI KOLATA
4       0393045218       E. J. W. BARBER
...            ...                   ...
271355  0440400988        PAULA DANZIGER
271356  0525447644            TERI SLOAT
271357  006008667X      CHRISTINE WICKER
271358  0192126040                 PLATO
271359  0767409752   CHRISTOPHER  BIFFLE

                                               Book-Title Year-Of-Publication  \
0                                     CLASSICAL MYTHOLOGY                2002
1                                            CLARA CALLAN                2001
2                                    DECISION IN NORMANDY                1991
3       FLU THE STORY OF THE GREAT INFLUENZA PANDEMIC ...                1999
4                                  THE MUMMIES OF URUMCHI                1999
...                                                   ...                 ...
271355                         THERE'S A BAT IN BUNK FIVE                1988
271356                            FROM ONE TO ONE HUNDRED                1991
271357  LILY DALE  THE TRUE STORY OF THE TOWN THAT TAL...                2004
271358                          REPUBLIC WORLD'S CLASSICS                1996
271359  A GUIDED TOUR OF RENE DESCARTES' MEDITATIONS O...                2000

                                               Publisher Language
0                                OXFORD UNIVERSITY PRESS       EN
1                                  HARPERFLAMINGO CANADA       EN
2                                        HARPERPERENNIAL       EN
3                                   FARRAR STRAUS GIROUX       EN
4                             W. W. NORTON &AMP; COMPANY       EN
...                                                  ...      ...
271355                   RANDOM HOUSE CHILDRENS PUB (MM)       EN
271356                                      DUTTON BOOKS       EN
271357                                HARPERSANFRANCISCO       EN
271358                           OXFORD UNIVERSITY PRESS       EN
271359  MCGRAW-HILL HUMANITIES/SOCIAL SCIENCES/LANGUAGES       IT

[271360 rows x 6 columns]>

In [26]:
books_data['Book-Title'].str.len().mean()

36.92450250589623

In [27]:
ratings_data.info

<bound method DataFrame.info of          User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]>

In [28]:

mean_count = count['Count'].mean()
print("Mean count:", mean_count)

NameError: name 'count' is not defined

In [29]:
users_data.info

<bound method DataFrame.info of         User-ID                            Location  Age
0             1                  nyc, new york, usa    0
1             2           stockton, california, usa   18
2             3     moscow, yukon territory, russia    0
3             4           porto, v.n.gaia, portugal   17
4             5  farnborough, hants, united kingdom    0
...         ...                                 ...  ...
278853   278854               portland, oregon, usa    0
278854   278855  tacoma, washington, united kingdom   50
278855   278856           brampton, ontario, canada    0
278856   278857           knoxville, tennessee, usa    0
278857   278858                dublin, n/a, ireland    0

[278858 rows x 3 columns]>

In [30]:
pd.merge(ratings_data, books_data, on='ISBN', how='left')

,User-ID,ISBN,Book-Rating,Book-Author,Book-Title,Year-Of-Publication,Publisher,Language
0,276725,034545104X,0,M. J. ROSE,FLESH TONES A NOVEL,2002,BALLANTINE BOOKS,EN
1,276726,0155061224,5,JUDITH RAE,RITES OF PASSAGE,2001,HEINLE,EN
2,276727,0446520802,0,NICHOLAS SPARKS,THE NOTEBOOK,1996,WARNER BOOKS,EN
3,276729,052165615X,3,PHILIP PROWSE,HELP! LEVEL 1,1999,CAMBRIDGE UNIVERSITY PRESS,EN
4,276729,0521795028,6,SUE LEATHER,THE AMSTERDAM CONNECTION LEVEL 4 CAMBRIDGE EN...,2001,CAMBRIDGE UNIVERSITY PRESS,EN
...,...,...,...,...,...,...,...,...
1149775,276704,1563526298,9,CLARK HOWARD,GET CLARK SMART THE ULTIMATE GUIDE FOR THE SA...,2000,LONGSTREET PRESS,FR
1149776,276706,0679447156,0,ANDREW WEIL,EIGHT WEEKS TO OPTIMUM HEALTH A PROVEN PROGRAM...,1997,ALFRED A. KNOPF,EN
1149777,276709,0515107662,10,CATHERINE COULTER,THE SHERBROOKE BRIDE BRIDE TRILOGY PAPERBACK,1996,JOVE BOOKS,EN
1149778,276721,0590442449,10,JERRY SPINELLI,FOURTH GRADE RATS,1996,SCHOLASTIC,EN
1149779,276723,05162443314,8,NaN,NaN,NaN,NaN,NaN

In [31]:
books_ratings_merge = pd.merge(books_data, ratings_data, on='ISBN', how='left')
books_ratings_merge

,ISBN,Book-Author,Book-Title,Year-Of-Publication,Publisher,Language,User-ID,Book-Rating
0,0195153448,MARK P. O. MORFORD,CLASSICAL MYTHOLOGY,2002,OXFORD UNIVERSITY PRESS,EN,2,0
1,0002005018,RICHARD BRUCE WRIGHT,CLARA CALLAN,2001,HARPERFLAMINGO CANADA,EN,8,5
2,0002005018,RICHARD BRUCE WRIGHT,CLARA CALLAN,2001,HARPERFLAMINGO CANADA,EN,11400,0
3,0002005018,RICHARD BRUCE WRIGHT,CLARA CALLAN,2001,HARPERFLAMINGO CANADA,EN,11676,8
4,0002005018,RICHARD BRUCE WRIGHT,CLARA CALLAN,2001,HARPERFLAMINGO CANADA,EN,41385,0
...,...,...,...,...,...,...,...,...
1032340,0440400988,PAULA DANZIGER,THERE'S A BAT IN BUNK FIVE,1988,RANDOM HOUSE CHILDRENS PUB (MM),EN,276463,7
1032341,0525447644,TERI SLOAT,FROM ONE TO ONE HUNDRED,1991,DUTTON BOOKS,EN,276579,4
1032342,006008667X,CHRISTINE WICKER,LILY DALE THE TRUE STORY OF THE TOWN THAT TAL...,2004,HARPERSANFRANCISCO,EN,276680,0
1032343,0192126040,PLATO,REPUBLIC WORLD'S CLASSICS,1996,OXFORD UNIVERSITY PRESS,EN,276680,0
1032344,0767409752,CHRISTOPHER BIFFLE,A GUIDED TOUR OF RENE DESCARTES' MEDITATIONS O...,2000,MCGRAW-HILL HUMANITIES/SOCIAL SCIENCES/LANGUAGES,IT,276680,0

In [38]:
mean_rating = books_ratings_merge.groupby('ISBN')['Book-Rating'].mean().reset_index(name = 'MeanRating')

books_ratings = pd.merge(books_data, mean_rating, how= 'inner', on = 'ISBN')

books_ratings

,ISBN,Book-Author,Book-Title,Year-Of-Publication,Publisher,Language,MeanRating
0,0195153448,MARK P. O. MORFORD,CLASSICAL MYTHOLOGY,2002,OXFORD UNIVERSITY PRESS,EN,0.0
1,0002005018,RICHARD BRUCE WRIGHT,CLARA CALLAN,2001,HARPERFLAMINGO CANADA,EN,4.928571
2,0060973129,CARLO D'ESTE,DECISION IN NORMANDY,1991,HARPERPERENNIAL,EN,5.0
3,0374157065,GINA BARI KOLATA,FLU THE STORY OF THE GREAT INFLUENZA PANDEMIC ...,1999,FARRAR STRAUS GIROUX,EN,4.272727
4,0393045218,E. J. W. BARBER,THE MUMMIES OF URUMCHI,1999,W. W. NORTON &AMP; COMPANY,EN,0.0
...,...,...,...,...,...,...,...
271355,0440400988,PAULA DANZIGER,THERE'S A BAT IN BUNK FIVE,1988,RANDOM HOUSE CHILDRENS PUB (MM),EN,7.0
271356,0525447644,TERI SLOAT,FROM ONE TO ONE HUNDRED,1991,DUTTON BOOKS,EN,4.0
271357,006008667X,CHRISTINE WICKER,LILY DALE THE TRUE STORY OF THE TOWN THAT TAL...,2004,HARPERSANFRANCISCO,EN,0.0
271358,0192126040,PLATO,REPUBLIC WORLD'S CLASSICS,1996,OXFORD UNIVERSITY PRESS,EN,0.0
271359,0767409752,CHRISTOPHER BIFFLE,A GUIDED TOUR OF RENE DESCARTES' MEDITATIONS O...,2000,MCGRAW-HILL HUMANITIES/SOCIAL SCIENCES/LANGUAGES,IT,0.0

In [39]:
number_of_ratings= books_ratings_merge.groupby('ISBN')['Book-Rating'].count().reset_index(name = 'NumberOfRatings')

books_ratings = pd.merge(books_ratings, number_of_ratings, how= 'inner', on = 'ISBN')

books_ratings

,ISBN,Book-Author,Book-Title,Year-Of-Publication,Publisher,Language,MeanRating,NumberOfRatings
0,0195153448,MARK P. O. MORFORD,CLASSICAL MYTHOLOGY,2002,OXFORD UNIVERSITY PRESS,EN,0.0,1
1,0002005018,RICHARD BRUCE WRIGHT,CLARA CALLAN,2001,HARPERFLAMINGO CANADA,EN,4.928571,14
2,0060973129,CARLO D'ESTE,DECISION IN NORMANDY,1991,HARPERPERENNIAL,EN,5.0,3
3,0374157065,GINA BARI KOLATA,FLU THE STORY OF THE GREAT INFLUENZA PANDEMIC ...,1999,FARRAR STRAUS GIROUX,EN,4.272727,11
4,0393045218,E. J. W. BARBER,THE MUMMIES OF URUMCHI,1999,W. W. NORTON &AMP; COMPANY,EN,0.0,1
...,...,...,...,...,...,...,...,...
271355,0440400988,PAULA DANZIGER,THERE'S A BAT IN BUNK FIVE,1988,RANDOM HOUSE CHILDRENS PUB (MM),EN,7.0,1
271356,0525447644,TERI SLOAT,FROM ONE TO ONE HUNDRED,1991,DUTTON BOOKS,EN,4.0,1
271357,006008667X,CHRISTINE WICKER,LILY DALE THE TRUE STORY OF THE TOWN THAT TAL...,2004,HARPERSANFRANCISCO,EN,0.0,1
271358,0192126040,PLATO,REPUBLIC WORLD'S CLASSICS,1996,OXFORD UNIVERSITY PRESS,EN,0.0,1
271359,0767409752,CHRISTOPHER BIFFLE,A GUIDED TOUR OF RENE DESCARTES' MEDITATIONS O...,2000,MCGRAW-HILL HUMANITIES/SOCIAL SCIENCES/LANGUAGES,IT,0.0,1

In [43]:
books_ratings.sort_values(by=['NumberOfRatings','MeanRating'], ascending=[False, False])

,ISBN,Book-Author,Book-Title,Year-Of-Publication,Publisher,Language,MeanRating,NumberOfRatings
26,0971880107,RICH SHAPERO,WILD ANIMUS,2004,TOO FAR,EN,1.019584,2502
408,0316666343,ALICE SEBOLD,THE LOVELY BONES A NOVEL,2002,"LITTLE, BROWN",EN,4.468726,1295
748,0385504209,DAN BROWN,THE DA VINCI CODE,2003,DOUBLEDAY,EN,4.652322,883
1105,0060928336,REBECCA WELLS,DIVINE SECRETS OF THE YA-YA SISTERHOOD A NOVEL,1997,PERENNIAL,EN,3.448087,732
522,0312195516,ANITA DIAMANT,THE RED TENT BESTSELLING BACKLIST,1998,PICADOR USA,EN,4.334716,723
...,...,...,...,...,...,...,...,...
271341,1874166633,LAURENCE GANE,INTRODUCING NIETZSCHE FOUNDATIONS IN CHILDREN'...,1998,NATL BOOK NETWORK,EN,<NA>,0
271342,0130897930,MARTY HALL,CORE WEB PROGRAMMING 2ND EDITION,2001,PRENTICE HALL PTR,EN,<NA>,0
271343,020130998X,JAMES RUMBAUGH,THE UNIFIED MODELING LANGUAGE REFERENCE MANUAL...,1998,ADDISON-WESLEY PROFESSIONAL,EN,<NA>,0
271344,2268032019,VLADIMIR VOLKOFF,PETITE HISTOIRE DE LA DÃ?Â©SINFORMATION,1999,EDITIONS DU ROCHER,PT,<NA>,0
271347,3442150663,VICTOR OSTROVSKY,DER MOSSAD.,2000,GOLDMANN,EN,<NA>,0

In [ ]:
with open('data/interim/books_ratings.pkl', 'wb') as f:
    pickle.dump(books_ratings, f)